### Register first user (admin)
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "rambo",
    "password": "admin123",
    "name": "Admin User",
    "email": "rambo@gmail.com",
    "role": "admin"
}

### Register regular user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "antonio guzman",
    "password": "user123",
    "name": "Regular User",
    "email": "lestersinja661@gmail.com",
    "phone": "1234567890"
}







### Login as admin
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "rambo@gmail.com",
    "password": "admin123"
}

### Login as user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "lestetsinjawatosia@gmail.com",
    "password": "user123"
}








### Create Update (Admin only)
POST http://localhost:8000/updates
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyYW1ib0BnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzQ0NjQ5NTF9.FEcmfNsqjVYQ6SCEHBVxXCz18r-4U5rgGDmxXhIQiSc
Content-Type: application/json

{
    "userId": 4,
    "content": "This is a test update from admin"
}

### Get All Updates
GET http://localhost:8000/updates
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyYW1ib0BnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzQ0NjQ5NTF9.FEcmfNsqjVYQ6SCEHBVxXCz18r-4U5rgGDmxXhIQiSc


### Edit Update (Admin only)
PUT http://localhost:8000/updates/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyYW1ib0BnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzQ0NjQ5NTF9.FEcmfNsqjVYQ6SCEHBVxXCz18r-4U5rgGDmxXhIQiSc
Content-Type: application/json


{
    "content": "This is an edited update"
}

### Delete Update (Admin only)
DELETE http://localhost:8000/updates/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyYW1ib0BnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzQ0NjQ5NTF9.FEcmfNsqjVYQ6SCEHBVxXCz18r-4U5rgGDmxXhIQiSc
















### Create Testimonial
POST http://localhost:8000/testimonials
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZXN0ZXRzaW5qYXdhdG9zaWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MzQ0NjU5Njh9.-WCLifpP4aRshQD_Uru4e-Y26ePu9JUSjQ0k5WE1rdk
Content-Type: application/json 

{
    "userId": 1,
    "text": "This is a test testimonial"
}

### Get All Testimonials
GET http://localhost:8000/testimonials
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZXN0ZXRzaW5qYXdhdG9zaWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MzQ0NjU5Njh9.-WCLifpP4aRshQD_Uru4e-Y26ePu9JUSjQ0k5WE1rdk

### Get Testimonial by ID
GET http://localhost:8000/testimonials/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZXN0ZXRzaW5qYXdhdG9zaWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MzQ0NjU5Njh9.-WCLifpP4aRshQD_Uru4e-Y26ePu9JUSjQ0k5WE1rdk

### Delete Testimonial (Admin only)
DELETE http://localhost:8000/testimonials/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyYW1ib0BnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MzQ0Njc0NTJ9.cObjMKzWWiU379jbChz_1XLHP19nK6KeCZs76xeY8Kc












